Fixes
FriskIsGit/SeleniumProjects pull request #1
Opened 2021-07-09 20:38 UTC by FriskIsGit

2021-07-12 20:04 UTC, karolgil requested changes

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +}
This should be a separate class, probably in a separate file.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +class Cursor{
Such a class (only private fields with getters and setters) is called a DTO - Data Transfer Object. Do not implement this by hand, use Lombok instead - specifically `@Data` annotation.

Doing so will help you refactor this class into:
```
@Data class CursorPosition {
  private int x;
  private int y;
}
```

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +class Cursor{
In general this class is not a `Cursor` implementation - it is a cursor position at best. I'd rename class and it's fields to `CursorPosition`, `x` and `y` respectively.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +class Performer {
This class is an unnecessary complication. Consider deleting it and using `Actions` directly. 

Line 18 would become:
```
private Actions actions;
```
Line 24:
```
actions = new Actions(driver);
```
And usage (e.g. line 43) will be:
```
actions.sendKeys(Keys.ARROW_DOWN).perform();
```

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    java.awt.Dimension screenDimensions = Toolkit.getDefaultToolkit().getScreenSize();
This field is used only in a single method. Consider defining a variable in that method instead of defining a field.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
Consider defining properties in [POM properties](https://maven.apache.org/pom.html#properties).

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +        performer = new Performer(driver);
Such initialization code should be placed in class constructor. Consider adding:
```
...
private AutomateBrowserActions () {
  cursor = new Cursor()
  driver = new ChromeDriver();
  performer = new Performer(driver);
}
...
```
and removing these two lines from this method.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void customizeBrowser(){
This method does not increase readability - in fact it decreases it slightly.

Compare current version:
```
    public static void main(String[] args) {
        new AutomateBrowserActions().customizeBrowser();
    }
```
with this method inlined
```
    public static void main(String[] args) {
        BrowserActions browserActions = new AutomateBrowserActions();

        browserActions.resizeAndRepositionWindow();
        browserActions.initiateDisplayThread();
        browserActions.denyGoogleCookies();
    }
```
The latter is easier to understand and maintain.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void changeBrowserLanguage(WebDriver driver){
Most of the methods in this class take `WebDriver` as an argument - it should be defined as a field and set up in the constructor.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private Performer performer;
This can probably be final as well.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private final long timeInMs = 60000;
Consider grouping static values and non-static fields, it increases readability:
```
private static final int WINDOW_WIDTH = 960;
private static final int WINDOW_HEIGHT = 720;
private static final int TIME_IN_MS = 60000;

private final Cursor cursor;
private final Performer performer;
```

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private final int windowWidth = 960;
Should be `static` - there is no reason to maintain that field on per-object basis. Same for other constant integers.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +        //denyCameraAccess(driver);
Code that's commented out can be safely removed - less maintenance over time.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void changeBrowserLanguage(WebDriver driver){
This method can be replaced by starting browser with the correct language in the first place - https://stackoverflow.com/a/18646033/1786019.

Current implementation is very prone to issues like Google re-designing their web interface and changing the position of your preferred language in the UI.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void changeDefaultSearchEngineTo(WebDriver driver,int element) {
Out of curiosity, what's the purpose of that method? In selenium we navigate to pages using their explicit URLs, so we can navigate to bing or duckduckgo if we want to search through those. Implementation is reaaaally hard to maintain in the current form - I expect these randon numbers like 36, 0.25 and 25 to work only on some specific screen/browser/system.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void denyLocationAccess(WebDriver driver){
AFAIK this can be replaced by a custom property - https://stackoverflow.com/a/21077039/1786019.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void denyCameraAccess(WebDriver driver){
Can be done through prefs as well I believe - https://stackoverflow.com/a/47836305/1786019.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +        List<WebElement> listOfWebElements = driver.findElements(By.xpath("//div[@class='uScs5d']//div[@data-is-touch-wrapper='true']"));
Can we get a better name for the list of web elements? What are these? Cookies check boxes? Something else?

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +        // //div[@class='uScs5d']//div[@data-is-touch-wrapper='true']
Remove commented out code.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void initiateDisplayThread(WebDriver driver) {
Consider some other method name, better reflecting the purpose of this - `logCursorPositionOverTime` or `continuouslyLogCursorPosition` maybe?

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void clickOnElement(WebElement webElement){
Such a method does not increase readability, consider inlining.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +            e.printStackTrace();
This isn't a good programming practice to ignore runtime exceptions. Consider adding `throws InterruptedException` to methods which need to use sleep and use `Thread.sleep(time)` directly.

Or even better - consider not sleeping at all.

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void movePointerWithinWindowBy(int x,int y){
We're calling it cursor everywhere else so maybe `moveCursorWithingWindowBy`?

2021-07-12 20:04 UTC, karolgil commented on src/main/java/AutomateBrowserActions.java
> +    private void clickPointerWithinWindow(){
Maybe just `click`?

2021-07-14 11:07 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +class Cursor{
IntelliJ refactoring feature is more intelligent than I thought
I feel like Lombok was made for lazy coders :P

2021-07-14 11:10 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +    private void changeBrowserLanguage(WebDriver driver){
should there be a getter for WebDriver field?

2021-07-14 11:25 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +}
1 file 1 class rule?

2021-07-14 11:34 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +    java.awt.Dimension screenDimensions = Toolkit.getDefaultToolkit().getScreenSize();
I changed it so that it's called whenever a function needs to resize the window to execute properly

2021-07-14 12:36 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +    private void changeDefaultSearchEngineTo(WebDriver driver,int element) {
For the sake of somehow bypassing google settings hidden in #shadow-root
These numbers are compatible with 3.141.59 version of chrome, current google UI and provided window dimensions i.e. screen resolution must be either equal or larger than given 960 by 720

2021-07-14 18:57 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
this proved to be more difficult than I thought

2021-07-14 23:50 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +    private void denyLocationAccess(WebDriver driver){
Doesn't change the defaults

2021-07-14 23:55 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +    private void denyLocationAccess(WebDriver driver){
JSONObject solution or any map solution have no effect on location settings

2021-07-14 23:56 UTC, FriskIsGit commented on src/main/java/AutomateBrowserActions.java
> +    private void changeBrowserLanguage(WebDriver driver){
This worked, surprisingly well.

2021-07-22 14:10 UTC, merged